= API
:example-caption!:
:source-highlighter: highlightjs
:toc: left
:toclevels: 5

== Introduction
Welcome to the control panel API documentation. This API documentation will provide sufficient information about the features and operations supported in the current release. This API is following the Restful conventions.

=== How to use
Requests must be made using the HTTPS protocol. The interface responds to different methods, depending on the action required.

=== HTTP Methods
The allowed methods are:

|===
| Method | description

| `GET`
| Used to get information about a resource

|===

[[http-status]]
=== HTTP Codes
The supported HTTP codes are:

|===
| Code | description

| `200 OK`
| The request ran successfully

| `201 Created`
| New feature was successfully created

| `202 Accepted`
| New feature successfully accepted

| `500 Internal Server Error`
| A generic error message, given when no more specific message is appropriate

|===

= Recursos - API
The API V1 features are detailed in this section.

include::queryController.adoc[]
include::tableController.adoc[]
include::viewController.adoc[]
